---
version: "2"

services:
    mact-nginx:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NGINX_VERSION: ${NGINX_VERSION?err}
        restart: on-failure
        env_file:
            - ../../.env
        networks:
            - shared_mact
            - proxy_network_mact
        volumes:
            - ../../public:/srv/mact/public:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.rule=HostRegexp(`web.mact.localhost`)"
            - "traefik.http.routers.frontend.priority=1000"
            - "traefik.http.routers.frontend.entrypoints=web_mact"
            - "traefik.http.routers.frontendhttps.rule=HostRegexp(`web.mact.localhost`)"
            - "traefik.http.routers.frontendhttps.priority=1"
            - "traefik.http.routers.frontendhttps.tls=true"
            - "traefik.http.routers.frontendhttps.entrypoints=websecure_mact"
            - "traefik.http.services.frontend.loadbalancer.server.port=80"
            - "traefik.docker.network=proxy_network_mact"
            - "Project=mact.web"
        logging:
            driver: "json-file"
            options:
                max-size: '100k'
                max-file: '20'
